### ISSUE TITLE
Weather (Sidebar) No Longer Displaying

### ISSUE THREAD

**Issue by valindria** [Kaelri/Enigma#100]
Hello,

The weather skin stopped working a couple of days ago and I'm not sure what happened to make it do that. I went into the options for it and changed all the cities to mine just to see what would happen (which was nothing, heh), I also restored the defaults, reselected my city and still experienced no change. System restart didn't help and neither did reinstalling the suite.

**Comment by TheseFineLeatherJackets** [comment]
I have also noticed this issue.

**Comment by Xundi007** [comment]
Hi,

The problem is, that the Yahoo Weather public API became discounted.
https://developer.yahoo.com/weather/
"To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting March 15, 2016."
If you try to go the url, that the Enigma Weather use, you will face this exact OAuth1 issue.
(In my case, just for example: http://weather.yahooapis.com/forecastrss?w=814055&u=c )

**Comment by massiliattak** [comment]
This is normal, Yahoo has modified its security: _"To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting March 15, 2016. Please update your API calls with OAuth 1 enabled (via the OAuth /v1/yql end point if using YQL) using your Yahoo App key and secret."_[ Cf Source](https://developer.yahoo.com/weather/ )...
BUT, there is still a solution: modify the url for the measure "MeasureYahooWeather" in the YahooWeather.inc file (@Resources\Measures), as below:

- Previously: ~~Url=http://weather.yahooapis.com/forecastrss?w=#CurrentCode#&u=#Unit#~~
- Now: Url=http://xml.weather.yahoo.com/forecastrss?w=#CurrentCode#&u=#Unit#

Voilà! :)

**Comment by valindria** [comment]
Well, hell. It works wonderfully again, I am super happy and appreciate your help!
